### PR TITLE
style: fixed text and responsive design (mobile view) for error 500 and error 400 pages

### LINKED ISSUE #1320: Side for teknisk feil: Oppdatere design
@LeneSundsbo commented on [Tue Oct 04 2022](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/636)

Følgende oppdateringer er ønskelig:
- All brødtekst på én og samme linje.
- Fjerne dekorstripene nederst i skjermbildet.
- Erstatte stripene øverst med ny fil (vedlagt)

[Designskisser for mobil](https://eggedosis.github.io/fdk-design/redirects/portal/other/500-m.html)
[Designskisser for desktop](https://eggedosis.github.io/fdk-design/redirects/portal/other/500.html)

### PR DESCRIPTION
**Pull request by hegeaal**
closes #1320

### CODE REVIEW

File: src/components/error-page/components/error-400/styled.ts [hunk 1]
```diff
@@ -24,10 +24,11 @@ const Error400 = styled.div`
 
   & p {
     font-size: ${theme.fontSize('FS20')};
+    display: inline;
   }
 
   & span {
-    display: flex;
+    max-width: 1140px;
```
Comment (terjesyl) [inline src/components/error-page/components/error-400/styled.ts:31]: Har vi en default-bredde/konstant definert noe sted? @jeffreiffers

**Review by pooriamehregan — APPROVED** [review]

**Review by NilsOveTen — APPROVED** [review]
