### PR TITLE
Fix/ha/sammenlig begrep button

### LINKED ISSUE #1940: Feature: Få "sammenlig begrep"-knapp til å støtte ny struktur
Følgefeil: Det er noe med sammenligningsknappen på begrep som gjør at "Sist publisert" ikke rendres dersom disse inkluderer et begrep. Se brukt av `<SearchHitData>`

image

image

image

### PR DESCRIPTION
**Pull request by hegeaal**
closes #1940

### CODE REVIEW

File: src/api/search-api/suggestions.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ export const getSearchSuggestions = (
   transport?: boolean,
   searchEntity?: string
 ) => {
+  console.log(searchEntity);
```
Comment (NilsOveTen) [inline src/api/search-api/suggestions.ts:9]:
```suggestion
```

Comment (NilsOveTen) [reply src/api/search-api/suggestions.ts:9]: Kan droppe hele den commiten

**Review by NilsOveTen — APPROVED** [review]
