### PR TITLE
fix: #1310 text beta on  banner too small

### LINKED ISSUE #1310: WCAG - Tekst "beta" er for liten
image

### PR DESCRIPTION
**Pull request by hegeaal**
fixes #1310

### CODE REVIEW

File: src/pages/search-page/tabs/components/tabs/styled.ts [hunk 1]
```diff
@@ -102,7 +102,7 @@ const BetaRibbon = styled.span`
   right: -40px;
   transform: rotate(45deg);
   padding: ${theme.spacing('S4')} ${theme.spacing('S40')};
-  font-size: 1rem;
+  font-size: 14px;
```
Comment (jeffreiffers) [inline src/pages/search-page/tabs/components/tabs/styled.ts:105]: Bruk theme.fontSize istedenfor px.

**Review by jeffreiffers — CHANGES_REQUESTED** [review]

File: src/pages/search-page/tabs/components/tabs/styled.ts (hunk 1 above)
Comment (hegeaal) [reply src/pages/search-page/tabs/components/tabs/styled.ts]: e890aad

**Review by jeffreiffers — APPROVED** [review]
